version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/lol/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: script/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu