version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/lol/
hooks:
  AfterInstall:
    - location: script/afterinstall.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: script/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu