export enum MAP_ID {
  TWISTED_TREELINE = 10,
  SUMMONER_RIFT = 11,
}

export enum GAME_QUEUE_ID {
  RIFT_SOLO_RANK = 420,
  RIFT_NORMAL = 430,
  RIFT_FLEX_RANK = 440,
}

export const LEAGUE_QUEUE_TYPE = {
  [GAME_QUEUE_ID.RIFT_SOLO_RANK]: 'RANKED_SOLO_5x5',
  [GAME_QUEUE_ID.RIFT_FLEX_RANK]: 'RANKED_FLEX_SR',
};

export const RIFT_ROLE = {
  DUO: 'DUO',
  DUO_CARRY: 'DUO_CARRY',
  DUO_SUPPORT: 'DUO_SUPPORT',
  NONE: 'NONE',
  SOLO: 'SOLO',
};

export enum LANE {
  UNKNOWN,
  TOP_LANE,
  MID_LANE,
  BOT_LANE,
  JUNGLE,
}

export const RIFT_LANE = {
  TOP: LANE.TOP_LANE,
  MIDDLE: LANE.MID_LANE,
  MID: LANE.MID_LANE,
  BOTTOM: LANE.BOT_LANE,
  JUNGLE: LANE.JUNGLE,
  NONE: LANE.UNKNOWN,
};

export enum POSITION {
  UNKNOWN,
  TOP,
  JUNGLE,
  MID,
  ADC,
  SUPPORT,
}

export const RIFT_POSITION = {
  [POSITION.UNKNOWN]: 'UNKNOWN',
  [POSITION.TOP]: 'TOP',
  [POSITION.JUNGLE]: 'JUNGLE',
  [POSITION.MID]: 'MID',
  [POSITION.ADC]: 'ADC',
  [POSITION.SUPPORT]: 'SUPPORT',
};
